source('~/Desktop/Coursera/EDA/Project1/ExData_Plotting1/plot1.R')
rm(list = ls())
source('~/Desktop/Coursera/EDA/Project1/ExData_Plotting1/plot2.R')
rm(list = ls())
source('~/Desktop/Coursera/EDA/Project1/ExData_Plotting1/plot3.R')
rm(list = ls())
source('~/Desktop/Coursera/EDA/Project1/ExData_Plotting1/plot4.R')
rm(list = ls())
print('done')